#!/bin/sh -eu

if ! stm8flash -c "${PROGRAMMER}" -p "${DEVICE}" -v "${PROGRAM}.ihx" 2>/dev/null; then
    stm8flash -c "${PROGRAMMER}" -p "${DEVICE}" -w "${PROGRAM}.ihx"
    stm8flash -c "${PROGRAMMER}" -p "${DEVICE}" -v "${PROGRAM}.ihx"
else
    echo "This firmware is already uploaded to the hardware."
fi
stm8flash -c "${PROGRAMMER}" -p "${DEVICE}" -R
